CREATE SEQUENCE seq_empregado
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE seq_departamento
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_projeto
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE seq_dependente
START WITH 1
INCREMENT BY 1;